# Copyright (c) 2025 MediDent Inventory Manager

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: medident-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medident_inventory
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - medident-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medident-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: medident_inventory
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-secret-key-change-in-production
      JWT_EXPIRES_IN: 1d
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    networks:
      - medident-network

  # Frontend Web Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    container_name: medident-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - medident-network

networks:
  medident-network:
    driver: bridge

volumes:
  postgres-data:
